version: '3'

services:
    python:
        container_name: python_example
        build:
            context: python
        volumes:
            - ../:/var/infrastructure
            - ~/.aws:/root/.aws
        command: /bin/bash
        tty: true